platform :ios, '7.0'

target "KidsGift" do
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    
    pod 'GoogleSignIn'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'RESideMenu'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'AFNetworking'

end
